blank_issues_enabled: true

contact_links:
  - name: MtF.wiki
    url: https://github.com/mtf-wiki/MtF-wiki/issues/new/choose
    about: MtF.wiki
  - name: kuaer.club
    url: https://github.com/mtf-wiki/kuaer.club
    about: 跨性别导航 kuaer.club
